const OK_MESSAGE = "Success";
const CREATED_MESSAGE = "Successfully Created!";
const UPDATE_MESSAGE = "Successfully Created!";
const NOTFOUND_MESSAGE = "Not Found";
const BADREQUEST_MESSAGE = "Bad Request";
const INTERNAL_SERVER_ERROR_MESSAGE = "Internal Server Error";
const BADREQUEST_USER_ALREADY_EXIST = "Item Already Exist";

export {
  OK_MESSAGE,
  CREATED_MESSAGE,
  UPDATE_MESSAGE,
  NOTFOUND_MESSAGE,
  BADREQUEST_MESSAGE,
  INTERNAL_SERVER_ERROR_MESSAGE,
  BADREQUEST_USER_ALREADY_EXIST,
};
